version: '2'
services:
    datalaketool-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        volumes:
            - ~/volumes/simlife/DataLakeTool/mongodb/:/data/db/
